# Generated by Django 4.0.4 on 2022-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
